var container = document.getElementById('designer');
var a = `{"workbook":{"activeSheet":"工作表sfss1","sheets":[{"name":"test1","selection":{"row":4,"col":3,"endRow":7,"endCol":6},"data":[["1",null,null,"1",null],["2",null,null,null,null],["ef",null,"efs",null,null],[null,null,null,null,null],[null,null,"dfsdf",null,null],[null,null,null,null,"fsdf"]],"rowHeights":[null,null,null,null,null,null],"colWidths":[50,50,50,50,50]}]}}`;

var foo = new SpreadSheet(container, `{
	"workbook":{
		"activeSheet":"工作ee表1",
		"sheets":[{
			"cellMetas":[[{
				"col":0,
				"dataType":{
					"correctFormat":true,
					"dateFormat":"YYYY-MM-DD",
					"typeName":"date"
				},
				"isFormula":false,
				"row":0,
				"sourceValue":"2015-07-07",
				"value":"2015-07-07"
			},{
				"col":1,
				"isFormula":false,
				"row":0
			},{
				"col":2,
				"isFormula":true,
				"row":0,
				"sourceValue":"=TEST",
				"value":"TRUE"
			},null],[{
				"col":0,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":1,
				"sourceValue":1.0,
				"value":"1"
			},{
				"col":1,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":1,
				"sourceValue":33.0,
				"value":"33"
			},null,null,{
				"col":4,
				"isFormula":false,
				"row":1
			},{
				"col":5,
				"isFormula":false,
				"row":1
			},{
				"col":6,
				"isFormula":false,
				"row":1
			},null],[{
				"col":0,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":2,
				"sourceValue":2.0,
				"value":"2"
			},null,null,null,{
				"col":4,
				"isFormula":false,
				"row":2
			},{
				"col":5,
				"isFormula":false,
				"row":2
			},{
				"col":6,
				"isFormula":false,
				"row":2
			},null],[{
				"col":0,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":3,
				"sourceValue":3.0,
				"value":"3"
			},null],[{
				"col":0,
				"isFormula":true,
				"row":4,
				"sourceValue":"=SUM(A2:A4)",
				"value":"6.0"
			},null],[],[null,{
				"col":1,
				"isFormula":false,
				"row":6
			},null],[null,null,null,{
				"col":3,
				"isFormula":false,
				"row":7
			},null],[null,null,null,{
				"col":3,
				"isFormula":false,
				"row":8
			},null]],
			"data":[[
				"2015-07-07",
				null,
				"=TEST",
				null
			],[
				1.0,
				33.0,
				null,
				null,
				null,
				null,
				null,
				null
			],[
				2.0,
				null,
				null,
				null,
				null,
				null,
				null,
				null
			],[
				3.0,
				null
			],[
				"=SUM(A2:A4)",
				null
			],[],[
				null,
				null,
				null
			],[
				null,
				null,
				null,
				null,
				null
			],[
				null,
				null,
				null,
				null,
				null
			]],
			"mergeCells":[{
				"col":4,
				"colspan":3,
				"row":1,
				"rowspan":2
			}],
			"name":"工作ee表1"
		},{
			"cellMetas":[[{
				"col":0,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":0,
				"sourceValue":1.0,
				"value":"1"
			},{
				"col":1,
				"isFormula":true,
				"row":0,
				"sourceValue":"=工作ee表1!A2",
				"value":"1.0"
			},null],[{
				"col":0,
				"dataType":{
					"correctFormat":false,
					"format":"0[.00]",
					"language":"zh-CN",
					"typeName":"numeric"
				},
				"isFormula":false,
				"row":1,
				"sourceValue":2.0,
				"value":"2"
			},null]],
			"data":[[
				1.0,
				"=工作ee表1!A2",
				null
			],[
				2.0,
				null
			]],
			"mergeCells":[],
			"name":"工作表2"
		},{
			"cellMetas":[[]],
			"data":[[]],
			"mergeCells":[],
			"name":"SUM(A1)"
		}]
	}
}`);
var wb = foo.getWorkbookInstance();

console.log(foo.getExchange());
